# Generated by Django 5.1.15 on 2026-08-25 12:03

import apps.notes.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_remove_subject_unique_subject_code_per_school_and_more'),
        ('tenants', '0003_schoolfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title / Chapter name of the note', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or instructions')),
                ('file', models.FileField(help_text='Document file (PDF, DOCX, PPTX, Images)', upload_to='school_notes/%Y/%m/', validators=[apps.notes.validators.validate_note_file_extension, apps.notes.validators.validate_note_file_size])),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Approval status of the note', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Reason provided by Class Teacher if rejected')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when note was approved or rejected', null=True)),
                ('division', models.ForeignKey(help_text='Class division this note is intended for', on_delete=django.db.models.deletion.CASCADE, related_name='subject_notes', to='academics.division')),
                ('faculty', models.ForeignKey(help_text='Faculty member who uploaded the note', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Class Teacher user who approved or rejected the note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_notes', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('subject', models.ForeignKey(help_text='Academic subject of the note', on_delete=django.db.models.deletion.PROTECT, related_name='subject_notes', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Note',
                'verbose_name_plural': 'Subject Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
