# Generated by Django 5.1.15 on 2026-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='tenant_user_requires_school',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Platform Super Admin'), ('SCHOOL_ADMIN', 'School Administrator'), ('FACULTY', 'School Faculty'), ('STUDENT', 'Student')], db_index=True, default='FACULTY', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['SCHOOL_ADMIN', 'FACULTY', 'STUDENT']), ('school__isnull', False)), ('role', 'SUPER_ADMIN'), _connector='OR'), name='tenant_user_requires_school'),
        ),
    ]
