# Generated by Django 5.1.15 on 2026-08-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0002_alter_faculty_designation'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PAID', 'Paid Leave')], help_text='Leave category (Casual, Sick, Paid).', max_length=20)),
                ('from_date', models.DateField(help_text='Start date of leave (inclusive).')),
                ('to_date', models.DateField(help_text='End date of leave (inclusive).')),
                ('reason', models.TextField(blank=True, default='', help_text='Reason/description for the leave request.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current state of the request.', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Explanation reason if rejected by School Admin.')),
                ('faculty', models.ForeignKey(help_text='Faculty member requesting leave.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='faculty.faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-from_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PAID', 'Paid Leave')], help_text='Type of leave allocated (Casual, Sick, Paid).', max_length=20)),
                ('allocated', models.PositiveIntegerField(default=0, help_text='Number of allocated leave days.')),
                ('faculty', models.ForeignKey(help_text='Faculty member who owns this leave allocation.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to='faculty.faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Leave Allocation',
                'verbose_name_plural': 'Leave Allocations',
                'ordering': ['faculty', 'leave_type'],
                'constraints': [models.UniqueConstraint(fields=('school', 'faculty', 'leave_type'), name='unique_faculty_leave_type_per_school')],
            },
        ),
    ]
