# Generated by Django 5.1.15 on 2026-08-25 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_schoolfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Headline or title of the announcement', max_length=200)),
                ('content', models.TextField(help_text='Detailed announcement message / body')),
                ('target_audience', models.CharField(choices=[('ALL', 'Everyone (All Roles)'), ('STUDENTS', 'Students Only'), ('FACULTY', 'Faculty Only')], default='ALL', help_text='Audience scope for this announcement', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this announcement is currently active and visible')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date and time')),
                ('author', models.ForeignKey(help_text='School Admin user who created the announcement', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'School Announcement',
                'verbose_name_plural': 'School Announcements',
                'ordering': ['-published_at'],
            },
        ),
    ]
