# Generated by Django 5.1.15 on 2026-08-30 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        ('tenants', '0003_schoolfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolannouncement',
            name='author',
            field=models.ForeignKey(help_text='School Admin / Principal user who created the announcement', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolannouncement',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('STUDENTS', 'Students only'), ('FACULTY', 'Faculty only')], default='ALL', help_text='Audience scope for this announcement (Everyone, Students only, Faculty only)', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolannouncement',
            name='title',
            field=models.CharField(help_text='Headline or title of the announcement / notice', max_length=200),
        ),
        migrations.CreateModel(
            name='AnnouncementAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when popup was dismissed')),
                ('announcement', models.ForeignKey(help_text='Announcement that was acknowledged', on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='announcements.schoolannouncement')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('user', models.ForeignKey(help_text='User who viewed / acknowledged the popup', on_delete=django.db.models.deletion.CASCADE, related_name='announcement_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement Acknowledgment',
                'verbose_name_plural': 'Announcement Acknowledgments',
                'ordering': ['-acknowledged_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'announcement', 'user'), name='unique_announcement_ack_per_user')],
            },
        ),
    ]
