# Generated by Django 5.1.15 on 2026-08-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0002_alter_faculty_designation'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name of the academic year (e.g. 2026-2027, 2026-27)', max_length=50)),
                ('start_date', models.DateField(help_text='Session start date')),
                ('end_date', models.DateField(help_text='Session end date')),
                ('is_current', models.BooleanField(default=False, help_text='Flag indicating the active academic year for attendance and class operations')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Division section code/name (e.g. A, B, C, Rose, Lotus)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this division is currently active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['standard__order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(help_text='Academic year for this class assignment', on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_allocations', to='academics.academicyear')),
                ('faculty', models.ForeignKey(help_text='Assigned Class Teacher', on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_allocations', to='faculty.faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('division', models.ForeignKey(help_text='Assigned class division', on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_allocations', to='academics.division')),
            ],
            options={
                'verbose_name': 'Class Teacher Allocation',
                'verbose_name_plural': 'Class Teacher Allocations',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Grade / Standard name (e.g. Standard 10, Grade 1, UKG)', max_length=50)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Numerical index for sequential sorting and promotion order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this standard is active for current academic operations')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Standard',
                'verbose_name_plural': 'Standards',
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.AddField(
            model_name='division',
            name='standard',
            field=models.ForeignKey(help_text='Standard / Grade this division belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='academics.standard'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Subject title (e.g. Mathematics, Science, Social Studies)', max_length=100)),
                ('code', models.CharField(help_text='Unique subject identifier code (e.g. MATH-01, SCI-10)', max_length=30)),
                ('subject_type', models.CharField(choices=[('CORE', 'Core Subject'), ('ELECTIVE', 'Elective / Optional')], default='CORE', help_text='Categorization of subject', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently taught')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTeacherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(help_text='Academic year for this subject assignment', on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_allocations', to='academics.academicyear')),
                ('division', models.ForeignKey(help_text='Class division', on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_allocations', to='academics.division')),
                ('faculty', models.ForeignKey(help_text='Assigned Subject Teacher', on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_allocations', to='faculty.faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('subject', models.ForeignKey(help_text='Subject taught', on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_allocations', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Teacher Allocation',
                'verbose_name_plural': 'Subject Teacher Allocations',
            },
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_academic_year_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='classteacherallocation',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'division'), name='unique_class_teacher_per_division_year'),
        ),
        migrations.AddConstraint(
            model_name='standard',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_standard_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('school', 'standard', 'name'), name='unique_division_per_standard_per_school'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_subject_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='subjectteacherallocation',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'division', 'subject'), name='unique_subject_teacher_per_division_subject_year'),
        ),
    ]
