# Generated by Django 5.1.15 on 2026-08-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty', '0002_alter_faculty_designation'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectteacherallocation',
            name='unique_subject_teacher_per_division_subject_year',
        ),
        migrations.AddConstraint(
            model_name='subjectteacherallocation',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'division', 'subject', 'faculty'), name='unique_subject_teacher_allocation'),
        ),
    ]
