# Generated by Django 5.1.15 on 2026-08-21 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_subjectteacherallocation_unique_subject_teacher_per_division_subject_year_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently active in this grade curriculum')),
                ('academic_year', models.ForeignKey(help_text='Academic session for this curriculum assignment', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('standard', models.ForeignKey(help_text='Grade / Standard to which the subject is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='academics.standard')),
                ('subject', models.ForeignKey(help_text='Subject from Global Subject Master', on_delete=django.db.models.deletion.PROTECT, related_name='class_curriculums', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Class Curriculum',
                'verbose_name_plural': 'Class Curriculums',
                'ordering': ['standard__order_index', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_year', 'standard', 'subject'), name='unique_curriculum_per_standard_year')],
            },
        ),
    ]
