# Generated by Django 5.1.15 on 2026-08-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classcurriculum'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_code_per_school',
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Optional unique subject identifier code (e.g. MATH-01, SCI-10)', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('school', 'code'), name='unique_subject_code_per_school'),
        ),
    ]
