# Generated by Django 5.1.15 on 2026-08-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_subject_unique_subject_code_per_school_and_more'),
        ('faculty', '0004_facultyformfieldconfig'),
        ('tenants', '0003_schoolfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], help_text='Day of the week (1=Mon, 6=Sat)')),
                ('period_number', models.PositiveIntegerField(help_text='Period number / sequence (e.g. 1, 2, 3...)')),
                ('start_time', models.TimeField(blank=True, help_text='Period start time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Period end time', null=True)),
                ('academic_year', models.ForeignKey(help_text='Academic session for this timetable', on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.academicyear')),
                ('division', models.ForeignKey(help_text='Class division schedule', on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.division')),
                ('faculty', models.ForeignKey(blank=True, help_text='Faculty assigned to teach this period', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_periods', to='faculty.faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('subject', models.ForeignKey(help_text='Subject taught during this period', on_delete=django.db.models.deletion.PROTECT, related_name='timetable_periods', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Class Timetable Slot',
                'verbose_name_plural': 'Class Timetable Slots',
                'ordering': ['day_of_week', 'period_number'],
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_year', 'division', 'day_of_week', 'period_number'), name='unique_period_per_division_day_year')],
            },
        ),
    ]
