# Generated by Django 5.1.15 on 2026-08-20 13:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_remove_subjectteacherallocation_unique_subject_teacher_per_division_subject_year_and_more'),
        ('faculty', '0002_alter_faculty_designation'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_number', models.CharField(db_index=True, help_text='General Register number (unique per school). Cannot be changed by Class Teacher.', max_length=50, verbose_name='GR Number')),
                ('roll_number', models.PositiveIntegerField(blank=True, help_text='Class roll number (unique per active division in academic year).', null=True, verbose_name='Roll Number')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10, verbose_name='Gender')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('', 'Unknown / Not Set')], default='', max_length=5, verbose_name='Blood Group')),
                ('guardian_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Guardian Name')),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Guardian Phone')),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=20, verbose_name='Emergency Contact')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('admission_date', models.DateField(default=django.utils.timezone.now, verbose_name='Admission Date')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.academicyear')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.division')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tenants.school')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.standard')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['standard__order_index', 'division__name', 'roll_number', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=15, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='academics.division')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_transfers', to='faculty.faculty')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfers', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_transfer_requests', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='students.student')),
                ('to_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='academics.division')),
                ('to_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfer_requests', to='academics.standard')),
            ],
            options={
                'verbose_name': 'Student Transfer Request',
                'verbose_name_plural': 'Student Transfer Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'gr_number'), name='unique_school_student_gr_number'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('roll_number__isnull', False)), fields=('school', 'academic_year', 'division', 'roll_number'), name='unique_active_roll_per_division_year'),
        ),
    ]
