# Generated by Django 5.1.15 on 2026-08-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Custom Fields'),
        ),
        migrations.CreateModel(
            name='StudentCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Field Label')),
                ('field_name', models.SlugField(max_length=100, verbose_name='Field Key')),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('SELECT', 'Dropdown Select')], default='TEXT', max_length=10, verbose_name='Field Type')),
                ('options', models.CharField(blank=True, help_text='Comma-separated options for Dropdown Select type', max_length=500, verbose_name='Dropdown Options')),
                ('is_required', models.BooleanField(default=False, verbose_name='Required')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_custom_fields', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Student Custom Field',
                'verbose_name_plural': 'Student Custom Fields',
                'ordering': ['order_index', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'field_name'), name='unique_school_student_custom_field')],
            },
        ),
    ]
