# Generated by Django 5.1.15 on 2026-08-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_custom_fields_studentcustomfield'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFormFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_roll_number', models.BooleanField(default=True, verbose_name='Show Roll Number')),
                ('show_gender', models.BooleanField(default=True, verbose_name='Show Gender')),
                ('show_dob', models.BooleanField(default=True, verbose_name='Show Date of Birth')),
                ('show_blood_group', models.BooleanField(default=True, verbose_name='Show Blood Group')),
                ('show_guardian_details', models.BooleanField(default=True, verbose_name='Show Guardian Details')),
                ('show_emergency_contact', models.BooleanField(default=True, verbose_name='Show Emergency Contact')),
                ('show_admission_date', models.BooleanField(default=True, verbose_name='Show Admission Date')),
                ('show_address', models.BooleanField(default=True, verbose_name='Show Address')),
                ('require_roll_number', models.BooleanField(default=False, verbose_name='Require Roll Number')),
                ('require_gender', models.BooleanField(default=False, verbose_name='Require Gender')),
                ('require_dob', models.BooleanField(default=False, verbose_name='Require Date of Birth')),
                ('require_blood_group', models.BooleanField(default=False, verbose_name='Require Blood Group')),
                ('require_guardian_details', models.BooleanField(default=False, verbose_name='Require Guardian Details')),
                ('require_emergency_contact', models.BooleanField(default=False, verbose_name='Require Emergency Contact')),
                ('require_admission_date', models.BooleanField(default=False, verbose_name='Require Admission Date')),
                ('require_address', models.BooleanField(default=False, verbose_name='Require Address')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_form_config', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Student Form Field Configuration',
                'verbose_name_plural': 'Student Form Field Configurations',
            },
        ),
    ]
