# Generated by Django 5.1.15 on 2026-08-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the school', max_length=255)),
                ('subdomain', models.SlugField(help_text='Unique subdomain slug (e.g. greenwood for greenwood.ourapp.com)', max_length=63, unique=True)),
                ('contact_email', models.EmailField(help_text='Primary administrative contact email', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this school account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Tenant',
                'verbose_name_plural': 'School Tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
