# Generated by Django 5.1.15 on 2026-08-22 15:03

import apps.tenants.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_image',
            field=models.ImageField(blank=True, help_text='School cover image displayed on login page', null=True, upload_to='school_branding/images/', validators=[apps.tenants.validators.validate_image_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'], message='Only image files (jpg, jpeg, png, gif, webp, svg) are allowed.')]),
        ),
        migrations.AddField(
            model_name='school',
            name='school_logo',
            field=models.ImageField(blank=True, help_text='School logo displayed in portal navigation header', null=True, upload_to='school_branding/logos/', validators=[apps.tenants.validators.validate_image_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'], message='Only image files (jpg, jpeg, png, gif, webp, svg) are allowed.')]),
        ),
    ]
