# Generated by Django 5.1.15 on 2026-08-23 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_school_image_school_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(db_index=True, help_text='Feature identifier key (e.g. faculty_leave, reports)', max_length=50, verbose_name='Feature Key')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this feature is active for this school', verbose_name='Is Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'School Feature Configuration',
                'verbose_name_plural': 'School Feature Configurations',
                'constraints': [models.UniqueConstraint(fields=('school', 'feature_key'), name='unique_school_feature_key')],
            },
        ),
    ]
