# Generated by Django 5.1.15 on 2026-08-29 05:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_classtimetable'),
        ('students', '0003_studentformfieldconfig'),
        ('tenants', '0003_schoolfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('PAYMENT_RECORDED', 'Payment Recorded'), ('PAYMENT_VOIDED', 'Payment Voided'), ('FEE_ASSIGNED', 'Fee Assigned'), ('DISCOUNT_APPLIED', 'Discount Applied'), ('WAIVER_APPLIED', 'Waiver Applied'), ('SCHEDULE_REGENERATED', 'Schedule Regenerated')], db_index=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='JSON metadata of before/after financial state')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_audit_logs', to='students.student')),
            ],
            options={
                'verbose_name': 'Fee Audit Log',
                'verbose_name_plural': 'Fee Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the fee category (e.g. Tuition Fee, Transport Fee, Lab Fee)', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Short code / identifier (e.g. TUITION, TRANSPORT)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this category covers')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is available for new fee structures')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Fee Category',
                'verbose_name_plural': 'Fee Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_number', models.PositiveSmallIntegerField(help_text='Sequential period index (1..12)')),
                ('period_name', models.CharField(help_text='Human readable label (e.g., April 2026, Q1 (Apr-Jun), Term 1, Full Year)', max_length=100)),
                ('due_date', models.DateField(help_text='Due date for this installment')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Payable amount for this installment', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount collected against this installment', max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], db_index=True, default='UNPAID', max_length=20)),
                ('academic_year', models.ForeignKey(help_text='Academic session', on_delete=django.db.models.deletion.PROTECT, related_name='fee_installments', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('student', models.ForeignKey(help_text='Student reference for direct lookup', on_delete=django.db.models.deletion.CASCADE, related_name='fee_installments', to='students.student')),
            ],
            options={
                'verbose_name': 'Fee Installment',
                'verbose_name_plural': 'Fee Installments',
                'ordering': ['period_number', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount collected', max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date payment was received')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online')], default='CASH', help_text='Mode of payment', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Cheque number, UTR, Bank transaction ref, or receipt reference', max_length=100)),
                ('receipt_number', models.CharField(db_index=True, help_text='Unique sequential receipt number per school', max_length=64)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('VOIDED', 'Voided')], db_index=True, default='SUCCESS', max_length=20)),
                ('void_reason', models.TextField(blank=True, help_text='Reason for voiding/reversing this payment')),
                ('voided_at', models.DateTimeField(blank=True, help_text='Timestamp when voided', null=True)),
                ('academic_year', models.ForeignKey(help_text='Academic session', on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='academics.academicyear')),
                ('installment', models.ForeignKey(blank=True, help_text='Specific installment this payment applies to (if single period)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fees.feeinstallment')),
                ('recorded_by', models.ForeignKey(help_text='Staff member / Admin who recorded the payment', on_delete=django.db.models.deletion.PROTECT, related_name='recorded_fee_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('student', models.ForeignKey(help_text='Student who paid', on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='students.student')),
                ('voided_by', models.ForeignKey(blank=True, help_text='Staff member who voided the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_fee_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fee Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name (e.g. Class 10 Tuition Fee 2026-27)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total base annual fee amount for this structure', max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('FULL_YEAR', 'Full-Year')], default='MONTHLY', help_text='Installment frequency (Monthly, Quarterly, Half-Yearly, Full-Year)', max_length=20)),
                ('due_day', models.PositiveSmallIntegerField(default=10, help_text='Day of the month/period when payment becomes due (1 to 28)')),
                ('description', models.TextField(blank=True, help_text='Optional internal notes or policy description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this fee structure is actively assigned')),
                ('academic_year', models.ForeignKey(help_text='Academic session this fee structure applies to', on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.academicyear')),
                ('division', models.ForeignKey(blank=True, help_text='Specific division (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.division')),
                ('fee_category', models.ForeignKey(help_text='Associated fee category', on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='fees.feecategory')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('standard', models.ForeignKey(blank=True, help_text='Target grade/standard (leave blank for all grades)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.standard')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Custom base amount overriding the standard fee amount (if applicable)', max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount applied to this student', max_digits=10)),
                ('discount_reason', models.CharField(blank=True, help_text='Reason for discount / scholarship', max_length=255)),
                ('waived_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount waived by administration', max_digits=10)),
                ('waiver_reason', models.CharField(blank=True, help_text='Reason for fee waiver', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this student fee assignment is active')),
                ('academic_year', models.ForeignKey(help_text='Academic year for this assignment', on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='academics.academicyear')),
                ('fee_structure', models.ForeignKey(help_text='Base fee structure', on_delete=django.db.models.deletion.PROTECT, related_name='student_assignments', to='fees.feestructure')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('student', models.ForeignKey(help_text='Student assigned this fee', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_fees', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Fee Assignment',
                'verbose_name_plural': 'Student Fee Assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='student_fee',
            field=models.ForeignKey(help_text='Parent student fee assignment', on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fees.studentfee'),
        ),
        migrations.AddConstraint(
            model_name='feecategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_fee_category_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='feepayment',
            constraint=models.UniqueConstraint(fields=('school', 'receipt_number'), name='unique_receipt_number_per_school'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('school', 'student', 'fee_structure'), name='unique_student_fee_structure_per_school'),
        ),
    ]
