# Generated by Django 5.1.15 on 2026-08-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Staff member / Admin who recorded the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_fee_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
