# Generated by Django 5.1.15 on 2026-08-12 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0002_alter_faculty_designation'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyBiometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', models.JSONField(help_text='512-dimensional normalized ArcFace float embedding vector (JSONB)')),
                ('enrolled_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last face enrollment or re-enrollment')),
                ('enrolled_by', models.ForeignKey(blank=True, help_text='School Admin who performed the enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_biometrics', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.OneToOneField(help_text='Faculty member this biometric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='biometric', to='faculty.faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Faculty Biometric',
                'verbose_name_plural': 'Faculty Biometrics',
            },
        ),
    ]
