# Generated by Django 5.1.15 on 2026-08-13 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0002_alter_faculty_designation'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Calendar date of attendance (timezone.localdate)')),
                ('check_in_time', models.DateTimeField(help_text='Timestamp of first face scan (check-in)')),
                ('check_out_time', models.DateTimeField(blank=True, help_text='Timestamp of last face scan (check-out)', null=True)),
                ('last_scan_at', models.DateTimeField(help_text='Timestamp of the most recent scan attempt (for cooldown lock)')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('EARLY_DEPARTURE', 'Early Departure')], default='PRESENT', help_text='Attendance status (calculated by schedule rules in Phase 8)', max_length=20)),
                ('match_confidence', models.FloatField(default=0.0, help_text='Cosine similarity score from face identification (0.0 to 1.0)')),
                ('device_info', models.CharField(blank=True, default='', help_text='Browser/device User-Agent string for audit trail', max_length=255)),
                ('faculty', models.ForeignKey(help_text='Faculty member this attendance record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='faculty.faculty')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-date', '-check_in_time'],
                'constraints': [models.UniqueConstraint(fields=('school', 'faculty', 'date'), name='unique_attendance_per_faculty_per_day')],
            },
        ),
    ]
