# Generated by Django 5.1.15 on 2026-08-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='early_departure',
            field=models.BooleanField(default=False, help_text='Whether check-out occurred before scheduled end_time minus grace period'),
        ),
    ]
