# Generated by Django 5.1.15 on 2026-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancelog_early_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of first face scan (check-in)', null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('EARLY_DEPARTURE', 'Early Departure'), ('LEAVE', 'Leave')], default='PRESENT', help_text='Attendance status (calculated by schedule rules in Phase 8)', max_length=20),
        ),
    ]
