# Generated by Django 5.1.15 on 2026-08-25 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_subject_unique_subject_code_per_school_and_more'),
        ('attendance', '0003_alter_attendancelog_check_in_time_and_more'),
        ('students', '0003_studentformfieldconfig'),
        ('tenants', '0003_schoolfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Calendar date of attendance')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day')], default='PRESENT', help_text='Attendance status marked by class teacher', max_length=20)),
                ('remarks', models.CharField(blank=True, default='', help_text='Optional remarks for absence or half day', max_length=255)),
                ('division', models.ForeignKey(help_text='Division of the student at the time of marking', on_delete=django.db.models.deletion.PROTECT, related_name='student_attendance_logs', to='academics.division')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Class teacher user who recorded or updated this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_attendances', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('student', models.ForeignKey(help_text='Student this attendance record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_logs', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Attendance Log',
                'verbose_name_plural': 'Student Attendance Logs',
                'ordering': ['-date', 'student__roll_number', 'student__full_name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'student', 'date'), name='unique_student_attendance_per_day')],
            },
        ),
    ]
