# Generated by Django 5.1.15 on 2026-08-12 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text='Globally unique email (matches User.email)', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('employee_code', models.CharField(db_index=True, help_text='Auto-generated or manual employee identifier', max_length=50)),
                ('department', models.CharField(help_text='Academic department (e.g. Science, Mathematics)', max_length=100)),
                ('designation', models.CharField(help_text='Job title (e.g. Senior Teacher, HOD)', max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active employment status (deactivation preserves history)')),
                ('is_face_enrolled', models.BooleanField(default=False, help_text='Phase 6 architecture hook — face vector enrollment status')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
                ('user', models.OneToOneField(blank=True, help_text='Linked User account (identity-only, no password login)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['first_name', 'last_name'],
                'constraints': [models.UniqueConstraint(fields=('school', 'employee_code'), name='unique_faculty_code_per_school')],
            },
        ),
        migrations.CreateModel(
            name='TenantSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_type', models.CharField(default='FACULTY', help_text='Sequence category (e.g. FACULTY, DEPARTMENT)', max_length=50)),
                ('last_value', models.PositiveIntegerField(default=0, help_text='Last assigned sequence number')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Tenant Sequence',
                'verbose_name_plural': 'Tenant Sequences',
                'constraints': [models.UniqueConstraint(fields=('school', 'sequence_type'), name='unique_tenant_sequence_type')],
            },
        ),
    ]
