# Generated by Django 5.1.15 on 2026-08-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Job title (e.g. Senior Teacher, HOD) — optional', max_length=100),
        ),
    ]
