# Generated by Django 5.1.15 on 2026-08-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_custom_fields_facultycustomfield'),
        ('tenants', '0002_school_school_image_school_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyFormFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_phone_number', models.BooleanField(default=True, verbose_name='Show Phone Number')),
                ('show_employee_code', models.BooleanField(default=True, verbose_name='Show Employee Code')),
                ('show_department', models.BooleanField(default=True, verbose_name='Show Department')),
                ('show_designation', models.BooleanField(default=True, verbose_name='Show Designation')),
                ('require_phone_number', models.BooleanField(default=False, verbose_name='Require Phone Number')),
                ('require_employee_code', models.BooleanField(default=False, verbose_name='Require Employee Code')),
                ('require_department', models.BooleanField(default=True, verbose_name='Require Department')),
                ('require_designation', models.BooleanField(default=False, verbose_name='Require Designation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_form_config', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Faculty Form Field Configuration',
                'verbose_name_plural': 'Faculty Form Field Configurations',
            },
        ),
    ]
