# Generated by Django 5.1.15 on 2026-08-13 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_attendancelog_early_departure'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(help_text='Original status before correction', max_length=20)),
                ('new_status', models.CharField(help_text='Updated status after correction', max_length=20)),
                ('old_check_in_time', models.DateTimeField(blank=True, help_text='Original check-in timestamp', null=True)),
                ('new_check_in_time', models.DateTimeField(blank=True, help_text='Updated check-in timestamp', null=True)),
                ('old_check_out_time', models.DateTimeField(blank=True, help_text='Original check-out timestamp', null=True)),
                ('new_check_out_time', models.DateTimeField(blank=True, help_text='Updated check-out timestamp', null=True)),
                ('reason', models.CharField(help_text='Mandatory business reason / explanation for audit trail', max_length=255)),
                ('attendance', models.ForeignKey(help_text='Attendance record being corrected', on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendancelog')),
                ('performed_by', models.ForeignKey(blank=True, help_text='School Admin who authorized and saved this correction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_corrections', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Attendance Correction Audit Log',
                'verbose_name_plural': 'Attendance Correction Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
