# Generated by Django 5.1.15 on 2026-08-13 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Calendar date of holiday exception')),
                ('description', models.CharField(help_text='Holiday name / reason (e.g. Independence Day)', max_length=255)),
                ('is_recurring_yearly', models.BooleanField(default=False, help_text='Whether this holiday repeats every year on the same month and day')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Holiday Exception',
                'verbose_name_plural': 'Holiday Exceptions',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('school', 'date'), name='unique_holiday_per_date_per_school')],
            },
        ),
        migrations.CreateModel(
            name='WorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday .. 6=Sunday)')),
                ('is_working_day', models.BooleanField(default=True, help_text='Whether faculty are scheduled to work on this day')),
                ('start_time', models.TimeField(default='08:00:00', help_text='Scheduled shift start time')),
                ('end_time', models.TimeField(default='16:00:00', help_text='Scheduled shift end time')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, help_text='Grace period window in minutes after start_time before LATE status')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.school', verbose_name='School Tenant')),
            ],
            options={
                'verbose_name': 'Working Schedule',
                'verbose_name_plural': 'Working Schedules',
                'ordering': ['day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('school', 'day_of_week'), name='unique_schedule_per_day_per_school')],
            },
        ),
    ]
